name: Dependency Updates

on:
  schedule:
    - cron: '0 9 * * 1'
  workflow_dispatch:
  push:
    paths:
      - 'package.json'

jobs:
  check-updates:
    name: Check for Dependency Updates
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
    
    - name: Install dependencies
      run: npm install
    
    - name: Check for outdated packages
      id: outdated
      run: |
        echo "📦 Checking for outdated packages..."
        npm outdated --json > outdated.json || true
        cat outdated.json
      continue-on-error: true
    
    - name: Upload outdated report
      uses: actions/upload-artifact@v4
      with:
        name: outdated-packages-report
        path: outdated.json
        retention-days: 30

  security-updates:
    name: Security Updates
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
    
    - name: Install dependencies
      run: npm install
    
    - name: Run security audit
      id: audit
      run: |
        echo "🔒 Running security audit..."
        npm audit --json > audit-report.json || true
        cat audit-report.json
      continue-on-error: true
    
    - name: Upload audit report
      uses: actions/upload-artifact@v4
      with:
        name: security-audit-report
        path: audit-report.json
        retention-days: 90
