name: Dependency Updates

on:
  schedule:
    # Run every Monday at 9:00 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:
  push:
    paths:
      - 'package.json'
      - 'package-lock.json'

jobs:
  check-updates:
    name: Check for Dependency Updates
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Check for outdated packages
      id: outdated
      run: |
        echo "📦 Checking for outdated packages..."
        npm outdated --json > outdated.json || true
        cat outdated.json
        echo "outdated_count=$(cat outdated.json | jq 'length')" >> $GITHUB_OUTPUT
      continue-on-error: true
    
    - name: Upload outdated report
      uses: actions/upload-artifact@v4
      with:
        name: outdated-packages-report
        path: outdated.json
        retention-days: 30

  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    needs: check-updates
    permissions:
      contents: write
      pull-requests: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install npm-check-updates
      run: npm install -g npm-check-updates
    
    - name: Update patch versions
      run: |
        echo "🔄 Updating patch versions..."
        ncu -u --target patch
        npm install
      continue-on-error: true
    
    - name: Run tests after update
      run: |
        echo "🧪 Testing updated dependencies..."
        node -c run.js
        node run.js
      timeout-minutes: 5
      continue-on-error: true
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore(deps): update dependencies'
        title: '🔄 Automated Dependency Updates'
        body: |
          ## Dependency Updates
          
          This PR contains automated dependency updates.
          
          ### Changes
          - Updated patch versions of dependencies
          - All tests passed successfully
          
          ### Review Checklist
          - [ ] Review updated dependencies
          - [ ] Verify compatibility
          - [ ] Check for breaking changes
          - [ ] Run manual tests if needed
          
          **Generated by GitHub Actions**
        branch: automated-dependency-updates
        delete-branch: true
        labels: dependencies, automated

  security-updates:
    name: Security Updates
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run security audit
      id: audit
      run: |
        echo "🔒 Running security audit..."
        npm audit --json > audit-report.json || true
        VULNERABILITIES=$(cat audit-report.json | jq '.metadata.vulnerabilities.total')
        echo "vulnerabilities=$VULNERABILITIES" >> $GITHUB_OUTPUT
        cat audit-report.json | jq '.metadata'
      continue-on-error: true
    
    - name: Apply security fixes
      if: steps.audit.outputs.vulnerabilities > 0
      run: |
        echo "🔧 Applying security fixes..."
        npm audit fix
        npm audit fix --force || true
    
    - name: Upload audit report
      uses: actions/upload-artifact@v4
      with:
        name: security-audit-report
        path: audit-report.json
        retention-days: 90
    
    - name: Create Security PR
      if: steps.audit.outputs.vulnerabilities > 0
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'fix(security): apply security updates'
        title: '🔒 Security Updates - Fix Vulnerabilities'
        body: |
          ## Security Updates
          
          This PR contains automated security fixes.
          
          ### Vulnerabilities Fixed
          Found ${{ steps.audit.outputs.vulnerabilities }} vulnerabilities
          
          ### Actions Taken
          - Ran `npm audit fix`
          - Applied automatic security patches
          
          **⚠️ IMPORTANT: Review these changes carefully before merging**
          
          **Generated by GitHub Actions**
        branch: security-updates
        delete-branch: true
        labels: security, critical, automated

  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Dependency Review
      uses: actions/dependency-review-action@v4
      with:
        fail-on-severity: moderate
        deny-licenses: GPL-2.0, LGPL-2.0
